### ISSUE TITLE
ppx file is not created with .exe extension

### ISSUE THREAD

**Issue by xavierzwirtz** [MinimaHQ/bs-log#9]
On windows, the final ppx file is created as just `ppx`, not `ppx.exe`. Bucklescript cant invoke the ppx without it ending in exe.

**Comment by alexfedoseev** [comment]
IIRC requires small update in CI script. I will look into this next week.

**Comment by alexfedoseev** [comment]
I published `bs-log@1.0.0-beta.1` with BS7 support & Windows fix. But I don't have Windows machine to test it. Let me know if you can try it out.
